[package]
name = "vst2info-tool"
version = "0.1.0"
edition = "2024"
"authors" = ["Jurek Raben"]
repository = "https://github.com/Jurek-Raben/DawProject-Tool"

[dependencies]
vst2 = "0.0.1"
base64 = "0.22.1"
json = "0.12.4"